### ISSUE TITLE
BillStatus XML: House Amendment to another House Amendment

### ISSUE THREAD

**Issue by amarnathm** [usgpo/bulk-data#18]
In https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/113/hr/BILLSTATUS-113hr152.xml  (HR 152, 113th Congress), the xml for House Amendment 4 (HAMDT 4) merges with Senate Amendment 4 (SAMDT 4). 

According to https://www.congress.gov/bill/113th-congress/house-bill/152/amendments?pageSort=asc,  HAMDT 4 is an amendment to HAMDT 3. 

The xml content for the amendment has the correct description and purpose for  HAMDT 4, but the data below it is for SAMDT 4 -- before the end-amendment tag for HAMDT 4.

**Comment by llaplant** [comment]
A similar issue was reported in the bill-status repository. We deployed a fix in our latest release but not all files have been reprocessed yet. I reprocessed the file you referenced above but I am on my mobile so verification of the reprocessed file is a little tricky. Could you verify that the issue is still in the reprocessed file or if the reprocess fixed the issue? If reprocess did not fix the issue, let me know and I will enter the issue under the bill-status repository. Thanks!

**Comment by amarnathm** [comment]
Looks great! Thanks!!
