### ISSUE TITLE
Missing bills

### ISSUE THREAD

**Issue by pelzhaus** [usgpo/bulk-data#22]
I noticed today that the bulk data seems to be missing [all bills](https://www.congress.gov/search?q={%22source%22:%22legislation%22,%22congress%22:%22115%22}) introduced in the House yesterday, September 28th (34 at time of writing). I can't find any of them in BILLSTATUS page, even though actions show up on congress.gov.

I haven't seen the delay in uploading before, is this typical?

**Comment by jonquandt** [comment]
This is likely due to an issue overnight (see https://github.com/usgpo/bill-status/issues/72) where one of our processing jobs hung overnight and prevented the rest from loading. We kicked off a reprocess about an hour ago and things should start flowing in normally again. 

I just saw that another batch came through about 10 minutes ago, and it looks like it includes a number of the bills you linked to. I'll do a bit more research to confirm.

**Comment by jonquandt** [comment]
last batch added over 300 bills, and we should be all caught up for that.
