### ISSUE TITLE
Updated Bill Status for H.R. 5515 (NDAA)

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bulk-data#30]
Good morning, 

The bill actions for NDAA being signed into law are up to date on the congress.gov bill page: https://www.congress.gov/bill/115th-congress/house-bill/5515?q=%7B%22search%22%3A%5B%22hr5515%22%5D%7D&r=1

But the latest file available for actions in the bulk data repository hasn't been updated since August 2: https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr5515.xml

Do you know when this will be made available, and what the expected delay time between congress.gov updates and bulk data updates? Thank you!

**Comment by llaplant** [comment]
@anerbovig do you mind closing this issue here and moving it to the bill status repository https://github.com/usgpo/bill-status/issues? More bill status operational folks from our team are associated with that repository. In the mean time we will begin looking. It is likely that the bill status file is in the batch that is processing this morning. Thank you!

**Comment by anerbovig** [comment]
Sure thing--thanks for pointing me in the right direction!
