### ISSUE TITLE
42 CFR for 2007 missing volume 3 in the bulk data

### ISSUE THREAD

**Issue by kaitlin** [usgpo/bulk-data#58]
Hello again, 

Similar to my earlier issue, I also discovered 2007 for 42 CFR is missing volume 3: https://www.govinfo.gov/bulkdata/CFR/2007/title-42

Thanks!
Kaitlin

**Comment by llaplant** [comment]
Apologize for the much delayed response. CFR-2007-title42-vol3 is only available in text and PDF formats due to the availability of source data. See https://www.govinfo.gov/app/details/CFR-2007-title42-vol3. XML is available for this volume beginning with the 2008 annual edition https://www.govinfo.gov/app/details/CFR-2008-title42-vol3.
