### ISSUE TITLE
XML Files Don't Contain All Versions of a Bill

### ISSUE THREAD

**Issue by dstringvc** [usgpo/bulk-data#7]
I've noticed that many of the BILLSTATUS and BILLSUM XML files don't show all versions of a bill.

For example, as of 10-Aug-2016, the collection result https://www.gpo.gov/fdsys/browse/collection.action?collectionCode=BILLS&browsePath=114%2Fhr%2F%5B1000+-+1099%5D&isCollapsed=false&leafLevelBrowse=false&isDocumentResults=true&ycord=0

shows 6 versions of H.R. 1020.
H.R. 1020 (Introduced in House)
H.R. 1020 (Engrossed in House)
H.R. 1020 (Referred in Senate)
H.R. 1020 (Reported in Senate)
H.R. 1020 (Engrossed Amendment Senate)
H.R. 1020 (Enrolled Bill)

However, the file BILLSUM-114hr1020.xml (attached) only shows 5 versions of the bill. 
[BILLSUM-114hr1020.zip](https://github.com/usgpo/bulk-data/files/411858/BILLSUM-114hr1020.zip)

How can we get all versions of a bill in the related XML files?

**Comment by 104PL104** [comment]
Do not expect a one-to-one map of bill text versions to bill summaries. Sometimes a bill summary might summarize a document other than a bill text - a committee or conference report, for example. Other times, as is the case with the RFS version of HR1020, because the text is the same as the text of the EH version there is no need to produce a new summary.

In the user guide you may be interested in reviewing  table 5 Mapping of LOC Summaries Version Codes and Action Description Text. Here's a link to the user guide https://github.com/usgpo/bill-status/blob/master/BILLSTATUS-XML_User_User-Guide.md

**Comment by dstringvc** [comment]
@104PL104 Thank you for the explanation! Very helpful!
