### ISSUE TITLE
Availability of 2021 CFR title 11

### ISSUE THREAD

**Issue by patphongs** [usgpo/bulk-data#82]
At the FEC, we are wondering when the 2021 CFR title 11 will be available to download from your [bulk data resources](https://www.govinfo.gov/bulkdata/CFR).

**Comment by jonquandt** [comment]
Unfortunately, I don't have any specific timeline information on the availability of 2021 CFR volumes. 

The CFR XML on our [bulkdata repository](https://www.govinfo.gov/bulkdata/CFR) is updated annually, in four major groups. 

Per our [help documentation](https://www.govinfo.gov/help/cfr#about)

>When is it updated?

>The CFR on govinfo is current with the published print version of the CFR. When the print editions are released, the online version is also made available. If a CFR Title or volume is not listed in the CFR browse, that volume has not yet been published.

>The 50 subject matter titles contain one or more individual volumes, which are updated once each calendar year, on a staggered basis. The annual update cycle is as follows:

> - titles 1-16 are revised as of January 1
> - titles 17-27 are revised as of April 1
> - titles 28-41 are revised as of July 1
> - titles 42-50 are revised as of October 1

Note that there is a delay between the "revised of" dates and the availability on the govinfo bulkdata repository, because there are editorial processes required to ensure these are up to date. These are not always predictable. Example of volume 1 for that title in the past few years. 

|Year|date added to govinfo|
|---|---|
|2020 CFR Title 11 volume 1| 2020-05-19|
|2019 CFR Title 11 volume 1| 2019-05-10|
|2019 CFR Title 11 volume 1|2018-02-27|

If you are looking for something that might be more timely, you may be interested in examining the eCFR. This is a regularly updated, unofficial editorial compilation of CFR material and Federal Register amendments.

https://www.govinfo.gov/bulkdata/ECFR/title-11
The latest version of the eCFR for title 11 is from 2021-03-10

I hope this is helpful.

**Comment by patphongs** [comment]
Hello again @jonquandt, the FEC depends on the [bulk data XML](https://www.govinfo.gov/bulkdata/CFR) for title 11 provided by GPO in order to update our [regulations application](https://www.fec.gov/regulations). The previous years, the bulk data was available in May. I know that you had said it would be late this year. Now that it's July, I was wondering if you have an update on when we can expect this? Thanks again for your help!

**Comment by llaplant** [comment]
Hi, unfortunately we don't have an update date yet. You may want to visit 
https://www.gpo.gov/how-to-work-with-us/agency/services-for-agencies/ofr-publishing-services under the "CFR Schedule" header for information about anticipated delivery dates for CFR Titles. Dates for the 2021 edition will be posted here when information becomes available.

**Comment by patphongs** [comment]
It's available now and we've reloaded our regs. Closing this issue, thanks!
